/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        fundo: {
          DEFAULT: 'var(--fundo-pagina)',
          pagina: 'var(--fundo-pagina)',
          superficie: 'var(--fundo-superficie)',
          superficie2: 'var(--fundo-superficie-2)',
          superficie3: 'var(--fundo-superficie-3)',
          inverso: 'var(--fundo-inverso)',
        },
        'fundo-card': 'var(--superficie-1)',
        texto: {
          DEFAULT: 'var(--texto-principal)',
          principal: 'var(--texto-principal)',
          secundario: 'var(--texto-secundario)',
          terciario: 'var(--texto-terciario)',
          inverso: 'var(--texto-inverso)',
          desabilitado: 'var(--texto-desabilitado)',
        },
        'texto-secundario': 'var(--texto-secundario)',
        borda: {
          DEFAULT: 'var(--borda-sutil)',
          sutil: 'var(--borda-sutil)',
          media: 'var(--borda-media)',
          forte: 'var(--borda-forte)',
          foco: 'var(--borda-foco)',
        },
        primaria: {
          DEFAULT: 'var(--cor-primaria)',
          hover: 'var(--cor-primaria-hover)',
          ativa: 'var(--cor-primaria-ativa)',
          suave: 'var(--cor-primaria-suave)',
          texto: 'var(--texto-sobre-primaria)',
        },
        'primaria-texto': 'var(--cor-primaria-texto)',
        sucesso: {
          DEFAULT: 'var(--sucesso)',
          fundo: 'var(--sucesso-fundo)',
        },
        info: {
          DEFAULT: 'var(--info)',
          fundo: 'var(--info-fundo)',
        },
        aviso: {
          DEFAULT: 'var(--aviso)',
          fundo: 'var(--aviso-fundo)',
        },
        erro: {
          DEFAULT: 'var(--erro)',
          fundo: 'var(--erro-fundo)',
        },
        perigo: 'var(--perigo)',
      },
      fontFamily: {
        sans: ['var(--fonte-sans)', 'var(--fonte-interface)', 'system-ui', 'sans-serif'],
        serif: ['var(--fonte-serif)', 'serif'],
        mono: ['var(--fonte-mono)', 'var(--fonte-numeros)', 'monospace'],
      },
      borderRadius: {
        none: 'var(--raio-none)',
        sm: 'var(--raio-sm)',
        DEFAULT: 'var(--raio-md)',
        md: 'var(--raio-md)',
        lg: 'var(--raio-lg)',
        xl: 'var(--raio-xl)',
        '2xl': 'var(--raio-2xl)',
        full: 'var(--raio-full)',
      },
      spacing: {
        0: 'var(--espaco-0)',
        1: 'var(--espaco-1)',
        2: 'var(--espaco-2)',
        3: 'var(--espaco-3)',
        4: 'var(--espaco-4)',
        5: 'var(--espaco-5)',
        6: 'var(--espaco-6)',
        8: 'var(--espaco-8)',
        10: 'var(--espaco-10)',
        12: 'var(--espaco-12)',
        16: 'var(--espaco-16)',
        20: 'var(--espaco-20)',
        24: 'var(--espaco-24)',
      },
      boxShadow: {
        1: 'var(--elevacao-1)',
        2: 'var(--elevacao-2)',
        3: 'var(--elevacao-3)',
        DEFAULT: 'var(--elevacao-1)',
        sm: 'var(--elevacao-1)',
        md: 'var(--elevacao-2)',
        lg: 'var(--elevacao-3)',
      },
    },
  },
  plugins: [],
}
