[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build -w backend"

[deploy]
startCommand = "npx prisma db push --skip-generate --accept-data-loss && node dist/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
