import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { RepositorioCotasPrisma } from '../src/services/ia/repositorioCotasPrisma';
import { concessaoVigente } from '../src/services/ia/concessao';
import { calcularFimCiclo } from '../src/domain/assinatura/regrasAssinatura';
import { ContextoIa } from '../src/services/ia/cotas';
import { ConfiguracaoConsumoIa } from '../src/services/ia/configuracaoConsumo';

const url = process.env.IA_TEST_DATABASE_URL;
if (!url || !/^postgresql:\/\/[^@]+@127\.0\.0\.1:55439\/valen_ia_test_concessao$/.test(url)) throw new Error('Somente banco isolado de concessões');
const db = new PrismaClient({ datasourceUrl: url });
const db2 = new PrismaClient({ datasourceUrl: url });
const config: ConfiguracaoConsumoIa = { mensagens: { BASICO: 100, PRO: 200 }, creditos: { BASICO: 2000000, PRO: 6000000 },
  custoCreditoMicrousd: 1, tarifaEntradaMicrousd: 400000, tarifaSaidaMicrousd: 1600000,
  modelo: 'fixture', tarifaVersao: 'fixture-v1', politicaVersao: 'fixture-v1' };
const repo = new RepositorioCotasPrisma(db, config), repo2 = new RepositorioCotasPrisma(db2, config);
const results: string[] = [];
async function fixture(grant = true, ended = false) {
  const b = await db.barbearia.create({ data: { nome: 'Concessão QA isolada', slug: randomUUID() } });
  const u = await db.usuario.create({ data: { nome: 'Rafael Almeida', email: randomUUID()+'@example.invalid', senha: 'fixture-sem-login', papel: 'ADMIN', barbeariaId: b.id } });
  const c: ContextoIa = { barbeariaId: b.id, usuarioId: u.id, papel: 'ADMIN' };
  const g = grant ? await db.iaConcessao.create({ data: { barbeariaId: b.id, inicio: new Date(Date.now()-10000), fim: new Date(Date.now()+(ended ? -1000 : 86400000)), mensagensLimite: 100, creditosLimite: 2000000, custoCreditoMicrousd: 1 } }) : null;
  return {c,g};
}
async function main() {
  const a = await fixture(), b = await fixture();
  const saldo = await repo.saldo(a.c);
  assert.equal(saldo.mensagensRestantes,100); assert.equal(saldo.creditosRestantes,2000000);
  assert.equal(saldo.renovaEm,null); assert.equal(saldo.vozSegundosRestantes,0);
  assert.equal(await db.assinaturaSaas.count({where:{barbeariaId:a.c.barbeariaId}}),0);
  const sem = await fixture(false), expirada = await fixture(true,true);
  await assert.rejects(repo.saldo(sem.c),/concessão/);
  await assert.rejects(repo.saldo(expirada.c),/concessão/);
  assert.equal(concessaoVigente(a.g,a.c.barbeariaId,new Date(a.g!.fim.getTime()-1),1),true);
  assert.equal(concessaoVigente(a.g,a.c.barbeariaId,a.g!.fim,1),false);
  assert.equal(concessaoVigente(a.g,b.c.barbeariaId,new Date(),1),false);
  await assert.rejects(new RepositorioCotasPrisma(db,{...config,custoCreditoMicrousd:2}).saldo(a.c),/concessão/);
  results.push('elegibilidade, ausência de assinatura, validade exclusiva e custo unitário');
  await assert.rejects(repo.saldo({...a.c,barbeariaId:b.c.barbeariaId}),/Acesso/);
  await assert.rejects(repo.reservarVoz(a.c,randomUUID(),60,100),/exclusiva/);
  await db.barbearia.update({where:{id:b.c.barbeariaId},data:{ativo:false}});
  await assert.rejects(repo.saldo(b.c),/Acesso/);
  results.push('isolamento, tenant inativo e voz bloqueada');
  const key=randomUUID();
  const same=await Promise.all(Array.from({length:8},(_,i)=>(i%2?repo:repo2).reservarTexto(a.c,key,'Olá')));
  assert.equal(new Set(same.map(r=>r.id)).size,1);
  const send=await Promise.all([repo.marcarEnvio(a.c,same[0].id),repo2.marcarEnvio(a.c,same[0].id)]);
  assert.equal(send.filter(Boolean).length,1);
  const uso={respostaProvedorId:randomUUID(),tokensEntrada:100,tokensSaida:20,mensagens:1,segundosVoz:0};
  await Promise.all([repo.liquidar(a.c,same[0].id,uso),repo2.liquidar(a.c,same[0].id,uso)]);
  assert.equal(await db.iaUso.count({where:{barbeariaId:a.c.barbeariaId}}),1);
  assert.equal((await repo.saldo(a.c)).mensagensRestantes,99);
  results.push('idempotência, concorrência de envio/liquidação e ledger único');
  const races=await Promise.allSettled(Array.from({length:109},(_,i)=>(i%2?repo:repo2).reservarTexto(a.c,randomUUID(),'Pergunta curta')));
  assert.equal(races.filter(r=>r.status==='fulfilled').length,99);
  assert.equal((await repo.saldo(a.c)).mensagensRestantes,0);
  assert.equal(await db.iaPeriodo.count({where:{concessaoId:a.g!.id}}),1);
  await assert.rejects(repo.reservarTexto(a.c,randomUUID(),'Excesso'),/Saldo insuficiente/);
  results.push('100 mensagens totais, reservas concorrentes e ausência de reset');
  await assert.rejects(db.iaConcessao.update({where:{id:a.g!.id},data:{fim:new Date(a.g!.fim.getTime()+1)}}),/imutavel/);
  await assert.rejects(db.iaConcessao.create({data:{...a.g!,id:randomUUID()}}),/Unique/);
  const p=await db.iaPeriodo.findFirstOrThrow({where:{concessaoId:a.g!.id}});
  await assert.rejects(db.iaPeriodo.update({where:{id:p.id},data:{mensagensLimite:101}}),/concessao/);
  await assert.rejects(db.iaPeriodo.create({data:{...p,id:randomUUID(),barbeariaId:b.c.barbeariaId}}),/concessao|Foreign key|Unique/);
  results.push('concessão imutável, limites persistidos e vínculo de tenant');
  const credito=await fixture();
  const caro=new RepositorioCotasPrisma(db,{...config,tarifaEntradaMicrousd:25000000});
  await caro.reservarTexto(credito.c,randomUUID(),'Primeira');
  await assert.rejects(caro.reservarTexto(credito.c,randomUUID(),'Segunda'),/Saldo insuficiente/);
  results.push('teto financeiro inclui reservas pendentes');
  const late=await fixture();
  const r=await repo.reservarTexto(late.c,randomUUID(),'Pendente');await repo.marcarEnvio(late.c,r.id);
  await db.iaConcessao.update({where:{id:late.g!.id},data:{revogada:true}});
  await assert.rejects(repo.reservarTexto(late.c,randomUUID(),'Após revogar'),/concessão/);
  await repo.liquidar(late.c,r.id,{...uso,respostaProvedorId:randomUUID()});
  await assert.rejects(db.iaConcessao.update({where:{id:late.g!.id},data:{revogada:false}}),/imutavel/);
  results.push('revogação impede novos pedidos e preserva liquidação pendente');
  const paid=await fixture();await repo.reservarTexto(paid.c,randomUUID(),'Concessão');
  const inicio=new Date(Date.now()-1000);
  await db.assinaturaSaas.create({data:{barbeariaId:paid.c.barbeariaId,plano:'PRO',periodicidade:'MENSAL',precoCicloCentavos:6999,status:'ATIVA',cicloInicio:inicio,cicloFim:calcularFimCiclo(inicio,'MENSAL')}});
  assert.equal((await repo.saldo(paid.c)).concessaoGratuita,null);
  assert.equal((await repo.saldo(paid.c)).mensagensRestantes,200);
  await repo.reservarTexto(paid.c,randomUUID(),'Ciclo pago');
  const old=await db.iaPeriodo.findFirstOrThrow({where:{concessaoId:paid.g!.id}});
  assert.equal(old.mensagensReservadas,1);
  results.push('ciclo pago preservado e priorizado sem reset da concessão');
  console.log(JSON.stringify({passed:results.length,results},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await db.$disconnect();await db2.$disconnect()});
