import assert from 'node:assert/strict';
const cicloFim=new Date('2026-10-15T15:00:00Z');
const assinatura:any={id:'s1',barbeariaId:'b1',assinaturaExternaId:'sub-1',plano:'PRO',periodicidade:'MENSAL',status:'ATIVA',cicloInicio:new Date('2026-09-15T15:00:00Z'),cicloFim};
const mudanca:any={id:'m1',assinaturaId:'s1',tipo:'PERIODICIDADE',status:'AGENDADA',efetivarEm:cicloFim,assinatura,planoDestino:'PRO',periodicidadeDestino:'ANUAL'};
let excede=false;let pendentes:any[]=[]; let antesLock: (()=>void)|null=null;
const db={mudancaAssinatura:{findUnique:async()=>mudanca,findMany:async()=>mudanca.status==='AGENDADA'?[mudanca]:[],update:async({data}:any)=>Object.assign(mudanca,data)},assinaturaSaas:{findUnique:async()=>assinatura,findMany:async()=>pendentes,update:async({data}:any)=>Object.assign(assinatura,data)},barbeiro:{count:async()=>excede?9:2},clienteBarbearia:{count:async()=>10},$queryRaw:async()=>{antesLock?.();antesLock=null;return[];},$transaction:async(ops:any)=>typeof ops==='function'?ops(db):Promise.all(ops)};
(globalThis as any).prisma={$extends:()=>db};
async function main(){
 const {AssinaturaOperacionalService:s}=await import('../src/services/assinaturaOperacional.service');
 let sincroniza='PENDENTE';let cancela='PENDENTE';let cobranca='PAGA';let cancelamentos=0;
 const p:any={configurado:true,atualizarRecorrencia:async()=>({estado:sincroniza}),cancelarRenovacao:async()=>{cancelamentos++;return{estado:cancela}},cancelarCobrancaPendente:async()=>({estado:cobranca})};
 await s.processarMudancasAgendadas(new Date('2026-10-16'),p);
 assert.equal(mudanca.status,'AGENDADA');assert.equal(assinatura.periodicidade,'MENSAL');
 sincroniza='CONFIRMADO';
 await s.processarMudancasAgendadas(new Date('2026-10-14'),p);
 assert.equal(mudanca.status,'AGENDADA','sincronizar futuro não antecipa benefícios');
 await s.processarMudancasAgendadas(new Date('2026-10-16'),p);
 assert.equal(mudanca.status,'EFETIVADA');assert.equal(assinatura.periodicidade,'ANUAL');
 assert.equal(assinatura.cicloFim,cicloFim,'sincronização não cria período pago sem pagamento');
 Object.assign(mudanca,{status:'AGENDADA',tipo:'DOWNGRADE',planoDestino:'BASICO'});excede=true;
 await s.processarMudancasAgendadas(new Date('2026-10-16'),p);
 assert.equal(mudanca.status,'AGENDADA','não encerrar local antes de confirmar cancelamento externo');
 cancela='CONFIRMADO';await s.processarMudancasAgendadas(new Date('2026-10-16'),p);
 assert.equal(mudanca.status,'CANCELADA');assert.equal(assinatura.status,'CONSULTA_EXPORTACAO');
 Object.assign(assinatura,{status:'PAGAMENTO_PENDENTE',ultimaCobrancaExternaId:'pay-1',toleranciaAte:cicloFim});pendentes=[assinatura];
 const antes=cancelamentos;await s.processarToleranciasVencidas(p,new Date('2026-10-16'));
 assert.equal(cancelamentos,antes,'cobrança paga não cancela assinatura por inadimplência');
 assert.equal(assinatura.status,'PAGAMENTO_PENDENTE');
 cobranca='PENDENTE';await s.processarToleranciasVencidas(p,new Date('2026-10-16'));assert.equal(cancelamentos,antes);
 cobranca='CONFIRMADO';await s.processarToleranciasVencidas(p,new Date('2026-10-16'));
 assert.equal(assinatura.status,'CONSULTA_EXPORTACAO');assert.equal(cancelamentos,antes+1);
 // A lista do job foi obtida antes de um webhook concluir a mudança.
 Object.assign(mudanca,{status:'AGENDADA',tipo:'PERIODICIDADE'});pendentes=[];
 const futuro=new Date('2027-10-15T15:00:00Z'); let puts=0;
 p.atualizarRecorrencia=async()=>{puts++;return{estado:'CONFIRMADO'}};
 antesLock=()=>{mudanca.status='EFETIVADA';assinatura.proximaCobrancaEm=futuro;assinatura.cicloInicio=cicloFim;assinatura.cicloFim=futuro;};
 await s.processarMudancasAgendadas(new Date('2026-10-16'),p);
 assert.equal(puts,0,'snapshot antigo não pode disparar alteração externa depois do pagamento');
 assert.equal(assinatura.proximaCobrancaEm,futuro);
 mudanca.status='AGENDADA';
 await s.processarMudancasAgendadas(new Date('2026-10-16'),p);
 assert.equal(puts,0,'ciclo avançado sem mudança marcada exige reconciliação, sem retrocesso');
 assert.equal(assinatura.cicloFim,futuro);
 let conflitos=0;
 const consultaOriginal=db.$queryRaw;
 db.$queryRaw=async()=>{if(conflitos++===0)throw {code:'P2010',meta:{code:'40001'}};return consultaOriginal();};
 await s.processarMudancasAgendadas(new Date('2026-10-16'),p);
 assert.equal(conflitos,2,'conflito serializável de SELECT FOR UPDATE é relido em nova transação');
 console.log('Mudanças externas: falhas preservam estado, sincronização antecipada sem benefícios, ciclo não pago não avança, downgrade cancela recorrência e pagamento impede tolerância indevida.');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
