import { PrismaClient } from '@prisma/client';
import { ContextoIa } from './cotas';
import { ErroDeNegocio } from '../../lib/erros';

type Artigo = { perfil: ContextoIa['papel']; assunto: string; titulo: string; rota: string; fonte: string; descricao: string; passos: string[]; limites?: string[]; quandoUsar?: string; evidenciaAcao?: { arquivo: string; trecho: string }[] };
export const VERSAO_GUIA = '2026-10-02.1';
// Fonte única da ajuda. Rotas e arquivos de origem são conferidos no teste.
export const guiaSistema: Artigo[] = [
  { perfil: 'ADMIN', assunto: 'LANCAR_PRODUTO', titulo: 'Registrar venda de produtos', rota: '/admin/vendas', fonte: 'frontend/src/pages/Vendas.tsx', quandoUsar: 'Lançar/vender produto, registrar venda, carrinho, desconto ou estorno. Não é cadastrar produto ou repor estoque.',
    descricao: 'A venda fica em Estoque → Nova venda de produtos. Finalizar venda baixa as unidades e registra a receita financeira. Cadastro e ajuste de quantidade não registram venda.',
    passos: ['Abra Estoque e selecione Nova venda de produtos.', 'Localize o produto e use Adicionar; confira as quantidades em Sua venda.', 'Informe o cliente se necessário, confira desconto, total e Forma de pagamento.', 'Clique em Finalizar venda.'],
    limites: ['Se “lançar produto” não distinguir venda, cadastro ou reposição, pergunte qual dessas operações a pessoa quer fazer.', 'Novo produto → Salvar produto cadastra o item; Editar produto → Quantidade → Salvar produto ajusta o saldo. Não use esses controles para registrar uma venda.', 'Serviços são registrados separadamente. O carrinho contém somente produtos e não integra o fechamento do atendimento.', 'Descontos em reais, porcentagem ou pontos dependem da simulação e das regras disponíveis; pontos exigem cliente elegível. O custo unitário e o desconto rateado ficam guardados na venda. Não há comissão de barbeiro neste fluxo.', 'Para estornar uma venda registrada, use Histórico de vendas → Estornar venda. Informe motivo e confirme a devolução dos produtos e o reembolso integral, então Confirmar estorno. O sistema devolve estoque e pontos usados e registra saída financeira, preservando o histórico. Não envia Pix nem cancela cobranças na operadora.', 'Não crie outra entrada manual no Financeiro para a mesma venda. A Valéria apenas orienta.'],
    evidenciaAcao: [{ arquivo: 'frontend/src/pages/Vendas.tsx', trecho: 'Finalizar venda' }, { arquivo: 'frontend/src/pages/Vendas.tsx', trecho: '"/estoque/vender-carrinho"' }, { arquivo: 'frontend/src/pages/Vendas.tsx', trecho: 'Somente produtos. Serviços são registrados separadamente.' }, { arquivo: 'backend/src/services/estoque.service.ts', trecho: 'data: { quantidade: { decrement: quantidade } }' }, { arquivo: 'backend/src/services/estoque.service.ts', trecho: 'custoUnitario: p.item.custo' }, { arquivo: 'backend/src/services/estoque.service.ts', trecho: 'categoria: CATEGORIA_VENDA_PRODUTO' }] },
  { perfil: 'ADMIN', assunto: 'CADASTRAR_PRODUTO', titulo: 'Cadastrar produto', rota: '/admin/vendas', fonte: 'frontend/src/pages/Vendas.tsx', quandoUsar: 'Cadastrar/criar produto, informar custo ou preço no catálogo. Não registrar venda.',
    descricao: 'Novo produto cadastra o item com saldo inicial, custo e preço. Não registra receita de venda nem despesa de compra.', passos: ['Abra Estoque e clique em Novo produto.', 'Preencha Nome, Categoria, Quantidade, Unidade, Mínimo para alerta, Custo unitário e Preço de venda.', 'Confira os dados e clique em Salvar produto.'], limites: ['Para vender um produto já cadastrado, use Adicionar no carrinho e Finalizar venda.', 'Cadastrar um custo não cria uma saída no Financeiro.'],
    evidenciaAcao: [{ arquivo: 'frontend/src/pages/Vendas.tsx', trecho: '> Novo produto' }, { arquivo: 'frontend/src/pages/Vendas.tsx', trecho: 'method: editando ? "PUT" : "POST"' }, { arquivo: 'backend/src/services/estoque.service.ts', trecho: 'return prisma.estoque.create' }] },
  { perfil: 'ADMIN', assunto: 'AJUSTAR_ESTOQUE', titulo: 'Ajustar quantidade em estoque', rota: '/admin/vendas', fonte: 'frontend/src/pages/Vendas.tsx', quandoUsar: 'Entrada, reposição, saída por perda ou ajuste da quantidade em estoque; não confundir com venda.',
    descricao: 'O controle existente é Editar produto: Quantidade define o saldo total, não a quantidade a somar ou subtrair. Não há formulário separado de movimentações de entrada/saída com motivo neste fluxo.', passos: ['Abra Estoque e use Editar no produto.', 'No formulário Editar produto, altere Quantidade para o saldo total correto. Exemplo: havia 10 e chegaram 5; informe 15.', 'Confira e clique em Salvar produto.'], limites: ['Esse ajuste não cria venda, receita ou despesa financeira nem um histórico separado de movimentações com motivo.', 'Para uma saída por venda, use o carrinho e Finalizar venda; para desfazer uma venda, use o estorno no Histórico de vendas.'],
    evidenciaAcao: [{ arquivo: 'frontend/src/pages/Vendas.tsx', trecho: '"Editar produto"' }, { arquivo: 'frontend/src/pages/Vendas.tsx', trecho: '["quantidade", "Quantidade", "number"]' }, { arquivo: 'frontend/src/pages/Vendas.tsx', trecho: 'url: editando ? `/estoque/${editando}` : "/estoque"' }, { arquivo: 'backend/src/services/estoque.service.ts', trecho: 'return prisma.estoque.update' }] },
  { perfil: 'ADMIN', assunto: 'LANCAR_SERVICO', titulo: 'Registrar serviço realizado', rota: '/admin/financeiro', fonte: 'frontend/src/pages/Financeiro.tsx',
    quandoUsar: 'Como lançar/registrar um serviço realizado, atendimento avulso ou produção manual; não é consultar produção nem cadastrar catálogo.',
    descricao: 'O lançamento manual de serviço realizado fica no Financeiro. Ele cria uma entrada financeira, com serviços e barbeiro vinculados quando informados. Não cria agendamento.',
    passos: ['Abra Financeiro no menu e clique em Lançamento. O formulário se chama Novo Lançamento.', 'Selecione Entrada. Marque os serviços realizados e selecione o barbeiro para atribuir a produção; informe o cliente quando aplicável.', 'Confira Categoria, Valor Bruto / Base, Desconto, Forma de Pagamento e Data. Aguarde o cálculo e confira o Valor Final.', 'Revise e clique em Registrar.'],
    limites: ['Barbeiros permite cadastrar profissionais e consultar produção; não tem ação para lançar um serviço.', 'Se o atendimento já está na agenda, conclua o agendamento existente em Agenda (/admin/agenda), usando Concluir Agendamento e Confirmar Pagamento. Isso já gera o financeiro; não duplique com um lançamento manual.', 'Cadastrar uma opção no catálogo é Serviços (/admin/servicos) → Novo serviço → Cadastrar, sem gerar receita.', 'Se não estiver claro se a pessoa quer registrar um atendimento realizado ou cadastrar um serviço no catálogo, faça essa pergunta breve antes de escolher o fluxo.', 'A Valéria não registra nem confirma nenhum desses dados.'],
    evidenciaAcao: [{ arquivo: 'frontend/src/pages/Financeiro.tsx', trecho: '<Plus size={14} /> Lançamento' }, { arquivo: 'frontend/src/pages/Financeiro.tsx', trecho: "await api.post('/financeiro', payload)" }, { arquivo: 'backend/src/routes/financeiro.routes.ts', trecho: "router.post('/', FinanceiroController.criar)" }, { arquivo: 'backend/src/services/financeiro.service.ts', trecho: 'return prisma.lancamentoFinanceiro.create' }] },
  { perfil: 'ADMIN', assunto: 'CONCLUIR_AGENDAMENTO', titulo: 'Concluir atendimento agendado', rota: '/admin/agenda', fonte: 'frontend/src/pages/Agenda.tsx',
    quandoUsar: 'Concluir serviço já agendado, receber pagamento de atendimento da agenda; não criar lançamento manual duplicado.',
    descricao: 'Concluir um agendamento registra seu fechamento e cria a entrada financeira correspondente.', passos: ['Abra Agenda e selecione o agendamento.', 'Use Concluir Agendamento quando a ação estiver disponível.', 'No formulário Concluir Serviço, confira pagamento e descontos e use Confirmar Pagamento.'], limites: ['Não lance o mesmo atendimento novamente no Financeiro.', 'Novo Agendamento reserva um horário; não é a conclusão de um serviço.'],
    evidenciaAcao: [{ arquivo: 'frontend/src/pages/Agenda.tsx', trecho: 'Concluir Agendamento' }, { arquivo: 'frontend/src/pages/Agenda.tsx', trecho: 'await api.put(`/agendamentos/${agendamentoSelecionado.id}`, dados)' }, { arquivo: 'frontend/src/components/ModalConcluirServico.tsx', trecho: 'Confirmar Pagamento' }, { arquivo: 'backend/src/services/agendamento.service.ts', trecho: 'await tx.lancamentoFinanceiro.create' }] },
  { perfil: 'ADMIN', assunto: 'AGENDA', titulo: 'Agenda', rota: '/admin/agenda', fonte: 'frontend/src/pages/Agenda.tsx', descricao: 'Organiza agendamentos por data e barbeiro.', passos: ['Abra Agenda no menu.', 'Para cadastrar, use Novo Agendamento e informe cliente, serviços, barbeiro e horário.', 'Abra um agendamento existente para ver as ações disponíveis.'] },
  { perfil: 'ADMIN', assunto: 'PRODUCAO', titulo: 'Consultar produção dos barbeiros', rota: '/admin/barbeiros', fonte: 'frontend/src/pages/Barbeiros.tsx', quandoUsar: 'Ver relatório, acompanhar ou comparar produção já registrada; nunca lançar serviço.', descricao: 'O relatório de produção soma serviços lançados após descontos, antes de comissão, por data financeira; inclui manuais consistentes. Não é caixa bancário nem comissão.', passos: ['Abra Barbeiros.', 'Abra a produção do profissional e escolha o período. Para comparar todos, peça o ranking à Valéria.'], limites: ['Esta tela consulta produção; não permite lançar serviços. Para orientação de lançamento, consulte LANCAR_SERVICO.', 'Produtos, cancelados, fechamentos duplicados e registros inconsistentes ficam fora do cálculo de produção.'] },
  { perfil: 'ADMIN', assunto: 'CAIXA', titulo: 'Financeiro', rota: '/admin/financeiro', fonte: 'frontend/src/pages/Financeiro.tsx', descricao: 'Registra entradas e saídas por data e meio de pagamento. Comissão é a parte do profissional; saldo de caixa não é lucro líquido.', passos: ['Abra Financeiro.', 'Clique em Lançamento para abrir Novo Lançamento; confira tipo, categoria, valor, data e forma de pagamento.', 'Revise os dados e use Registrar.'], limites: ['Para registrar um serviço realizado com profissional, consulte LANCAR_SERVICO.', 'A Valéria orienta, mas não registra lançamentos.', 'Recebimentos são os valores informados no sistema, sem conciliação bancária automática.'] },
  { perfil: 'ADMIN', assunto: 'COMISSOES', titulo: 'Comissões', rota: '/admin/barbeiros', fonte: 'frontend/src/pages/Barbeiros.tsx', descricao: 'O cadastro do barbeiro tem percentual de comissão. Os lançamentos guardam a comissão histórica aplicada.', passos: ['Abra Barbeiros para conferir o percentual do profissional.', 'Use os relatórios de produção e financeiro para conferir valores históricos.'], limites: ['Mudar o percentual atual não significa recalcular o histórico.'] },
  { perfil: 'ADMIN', assunto: 'ESTOQUE', titulo: 'Estoque e vendas de produtos', rota: '/admin/vendas', fonte: 'frontend/src/pages/Vendas.tsx', descricao: 'Controla produtos, quantidades, custos, preços, carrinho e histórico de vendas.', passos: ['Abra Estoque no menu, cujo endereço é /admin/vendas.', 'Use Novo produto para cadastrar ou adicione produtos ao carrinho para vender.', 'No Histórico de vendas, confira a venda e use Estornar venda quando necessário.'], limites: ['Estorno não é exclusão do histórico.', 'Margem bruta usa custo histórico e desconto da venda; preço de tabela atual não prova preço passado.'] },
  { perfil: 'ADMIN', assunto: 'CLIENTES', titulo: 'Clientes', rota: '/admin/clientes', fonte: 'frontend/src/pages/Clientes.tsx', descricao: 'Consulta e administra os clientes vinculados à barbearia.', passos: ['Abra Clientes.', 'Localize a pessoa antes de abrir o cadastro e as ações disponíveis.'], limites: ['Registros com histórico devem ser preservados; não trate desativar como apagar histórico.'] },
  { perfil: 'ADMIN', assunto: 'SERVICOS', titulo: 'Cadastrar serviço no catálogo', rota: '/admin/servicos', fonte: 'frontend/src/pages/Servicos.tsx', quandoUsar: 'Cadastrar/criar serviço no catálogo, nome, preço ou duração; não registrar serviço realizado.', descricao: 'Mantém as opções do catálogo. Cadastrar um serviço não registra atendimento, produção ou receita.', passos: ['Abra Serviços e clique em Novo serviço.', 'Preencha nome, descrição, preço e duração; confira a cor.', 'Clique em Cadastrar.'], limites: ['Para lançar um serviço já realizado, consulte LANCAR_SERVICO; para marcar horário, consulte AGENDA.'], evidenciaAcao: [{ arquivo: 'frontend/src/pages/Servicos.tsx', trecho: '<Plus size={18} /> Novo serviço' }, { arquivo: 'frontend/src/pages/Servicos.tsx', trecho: "await api.post('/servicos'" }, { arquivo: 'frontend/src/pages/Servicos.tsx', trecho: '>Cadastrar</button>' }, { arquivo: 'backend/src/services/servico.service.ts', trecho: 'return prisma.servico.create' }] },
  { perfil: 'ADMIN', assunto: 'FIDELIDADE', titulo: 'Fidelidade', rota: '/admin/fidelidade', fonte: 'frontend/src/pages/admin/Fidelidade.tsx', descricao: 'Configura regras de pontos, recompensas e acompanha o histórico.', passos: ['Abra Fidelidade.', 'Escolha a área de regras, recompensas ou histórico conforme o que precisa conferir.'], limites: ['Pontos e descontos dependem das regras configuradas; não prometa saldo ou resgate sem consulta autorizada.'] },
  { perfil: 'ADMIN', assunto: 'RELATORIOS', titulo: 'Relatórios', rota: '/admin/relatorios', fonte: 'frontend/src/pages/Relatorios.tsx', descricao: 'Consulta resultados com filtros. Produção, receita de produtos, comissão e recebimentos são medidas diferentes.', passos: ['Abra Relatórios.', 'Defina o período e os filtros antes de comparar os valores.'] },
  { perfil: 'ADMIN', assunto: 'CONFIGURACOES', titulo: 'Configurações', rota: '/admin/configuracoes', fonte: 'frontend/src/pages/Configuracoes.tsx', descricao: 'Organiza dados da barbearia, funcionamento, regras do sistema e assinatura.', passos: ['Abra Configurações.', 'Selecione Barbearia, Funcionamento, Sistema ou Assinatura conforme a alteração.'], limites: ['A Valéria não altera configurações nem permissões.'] },
  { perfil: 'ADMIN', assunto: 'ASSINATURA', titulo: 'Assinatura', rota: '/admin/configuracoes?secao=assinatura', fonte: 'frontend/src/pages/Configuracoes.tsx', descricao: 'Exibe plano, cobrança e cancelamento da assinatura.', passos: ['Abra Configurações e selecione Assinatura.', 'Confira o estado mostrado antes de solicitar mudanças.'], limites: ['Acesso de consulta/exportação pode bloquear alterações. O guia não modifica plano nem cobrança.'] },
  { perfil: 'ADMIN', assunto: 'CHAT', titulo: 'Chat com clientes', rota: '/admin/chat', fonte: 'frontend/src/pages/admin/AdminChat.tsx', descricao: 'Conversas humanas com clientes vinculados.', passos: ['Abra Chat.', 'Selecione a conversa antes de enviar uma mensagem.'], limites: ['O chat humano é separado da conversa com a Valéria.'] },
  { perfil: 'BARBEIRO', assunto: 'AGENDA', titulo: 'Minha agenda', rota: '/barbeiro/agenda', fonte: 'frontend/src/pages/barbeiro/BarbeiroAgenda.tsx', descricao: 'Consulta a agenda do barbeiro autenticado.', passos: ['Abra Agenda no menu do barbeiro.', 'Selecione a data e confira os atendimentos.'], limites: ['Não dá acesso à agenda administrativa de outros profissionais.'] },
  { perfil: 'BARBEIRO', assunto: 'LANCAR_PRODUTO', titulo: 'Produtos no perfil do barbeiro', rota: '/barbeiro/hoje', fonte: 'frontend/src/pages/barbeiro/BarbeiroHoje.tsx', quandoUsar: 'Perguntas sobre lançar, vender, cadastrar produto ou ajustar estoque.', descricao: 'Este perfil não tem cadastro, venda ou ajuste de estoque de produtos. Concluir Atendimento registra serviços, não produtos.', passos: ['Solicite ao administrador o registro da venda, cadastro ou ajuste de produto.'], limites: ['Hoje é a tela de atendimentos de serviços do profissional; não tem formulário de produtos. Não forneça caminhos administrativos nem prometa comissão de produtos.'] },
  { perfil: 'BARBEIRO', assunto: 'LANCAR_SERVICO', titulo: 'Concluir meu atendimento', rota: '/barbeiro/hoje', fonte: 'frontend/src/pages/barbeiro/BarbeiroHoje.tsx', quandoUsar: 'Registrar/concluir serviço realizado pelo barbeiro; somente atendimento próprio existente.', descricao: 'O barbeiro conclui seus próprios atendimentos do dia em Hoje. A conclusão gera o lançamento financeiro e a comissão.', passos: ['Abra Hoje e localize seu atendimento.', 'Clique em Concluir atendimento no destaque ou Concluir na lista.', 'Confira o formulário Concluir atendimento e use Confirmar conclusão.'], limites: ['Este perfil não tem formulário de lançamento financeiro manual nem cadastro do catálogo. Para serviço avulso sem agendamento, procure o administrador.', 'A Valéria apenas orienta, sem confirmar atendimento ou pagamento.'], evidenciaAcao: [{ arquivo: 'frontend/src/pages/barbeiro/BarbeiroHoje.tsx', trecho: 'Concluir atendimento' }, { arquivo: 'frontend/src/components/barbeiro/BarberCheckout.tsx', trecho: 'await barbeiroApi.post(`/barbeiro/concluir-agendamento/${a.id}`' }, { arquivo: 'frontend/src/components/barbeiro/BarberCheckout.tsx', trecho: 'Confirmar conclusão' }, { arquivo: 'backend/src/services/barbeiroApp.service.ts', trecho: 'agendamentoOriginal.barbeiroId !== barbeiroId' }, { arquivo: 'backend/src/services/barbeiroApp.service.ts', trecho: 'await tx.lancamentoFinanceiro.create' }] },
  { perfil: 'BARBEIRO', assunto: 'HOJE', titulo: 'Atendimentos de hoje', rota: '/barbeiro/hoje', fonte: 'frontend/src/pages/barbeiro/BarbeiroHoje.tsx', descricao: 'Acompanha os atendimentos do dia do profissional autenticado.', passos: ['Abra Hoje.', 'Abra um atendimento para conferir as ações que o sistema permite.'] },
  { perfil: 'BARBEIRO', assunto: 'COMISSOES', titulo: 'Minhas comissões', rota: '/barbeiro/comissoes', fonte: 'frontend/src/pages/barbeiro/BarbeiroComissoes.tsx', descricao: 'Exibe valores e lançamentos de comissão do próprio profissional.', passos: ['Abra Comissões.', 'Ajuste início e fim e confira o Histórico do período.'], limites: ['Comissão não é o valor total produzido nem o caixa da barbearia.', 'A Valéria orienta onde consultar; a ferramenta administrativa de dados não está disponível neste perfil.'] },
  { perfil: 'BARBEIRO', assunto: 'PERFIL', titulo: 'Meu perfil', rota: '/barbeiro/perfil', fonte: 'frontend/src/pages/barbeiro/BarbeiroPerfil.tsx', descricao: 'Informações do barbeiro autenticado.', passos: ['Abra Perfil.', 'Confira os campos e controles disponíveis para sua conta.'] },
  { perfil: 'CLIENTE', assunto: 'AGENDA', titulo: 'Agendar e acompanhar', rota: '/cliente/barbearia/:barbeariaId/agendar', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaAgendar.tsx', descricao: 'Permite escolher serviços, profissional e horário disponível na barbearia selecionada.', passos: ['Na barbearia, abra Agendar.', 'Escolha serviços, profissional e horário; confira o resumo antes de confirmar.', 'Volte a Início para acompanhar seus agendamentos.'], limites: ['A Valéria não conhece disponibilidade em tempo real nem confirma agendamentos por conversa.'] },
  { perfil: 'CLIENTE', assunto: 'LANCAR_PRODUTO', titulo: 'Produtos com a equipe', rota: '/cliente/barbearia/:barbeariaId/chat', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaChat.tsx', quandoUsar: 'Perguntas sobre lançar, comprar, vender, cadastrar produto ou ajustar estoque.', descricao: 'O cliente não tem formulário de venda, cadastro ou ajuste de produtos neste perfil.', passos: ['Use Falar com a barbearia para consultar a equipe sobre produtos.'], limites: ['Não forneça caminhos administrativos, confirme venda ou prometa disponibilidade.'] },
  { perfil: 'CLIENTE', assunto: 'LANCAR_SERVICO', titulo: 'Registro de serviço pela equipe', rota: '/cliente/barbearia/:barbeariaId/chat', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaChat.tsx', quandoUsar: 'Cliente pergunta como lançar/registrar serviço realizado ou cadastrar catálogo.', descricao: 'O cliente não lança produção, não confirma pagamento do atendimento e não cadastra opções de serviço.', passos: ['Use Falar com a barbearia para solicitar à equipe a conferência de um serviço realizado.', 'Se deseja apenas marcar um horário, use Agendar.'], limites: ['Não forneça caminhos administrativos nem prometa que o registro foi feito.'] },
  { perfil: 'CLIENTE', assunto: 'FIDELIDADE', titulo: 'Minha fidelidade', rota: '/cliente/barbearia/:barbeariaId/fidelidade', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaFidelidade.tsx', descricao: 'Mostra pontos e recompensas do próprio cliente nessa barbearia.', passos: ['Abra Fidelidade.', 'Confira saldo e recompensas disponíveis.', 'Para solicitar uma recompensa, use Resgatar e siga a confirmação exibida; o caixa confirma o resgate na visita.'], limites: ['Regras e elegibilidade dependem da configuração e do saldo real.'] },
  { perfil: 'CLIENTE', assunto: 'HISTORICO', titulo: 'Meu histórico', rota: '/cliente/barbearia/:barbeariaId/historico', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaHistorico.tsx', descricao: 'Consulta o histórico do próprio cliente na barbearia.', passos: ['Abra o histórico dentro da barbearia selecionada.', 'Confira os registros exibidos para sua conta.'] },
  { perfil: 'CLIENTE', assunto: 'CHAT', titulo: 'Falar com a barbearia', rota: '/cliente/barbearia/:barbeariaId/chat', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaChat.tsx', descricao: 'Canal de conversa humana com a barbearia.', passos: ['Use Falar com a barbearia, o botão de chat.', 'Escreva sua mensagem para a equipe.'], limites: ['A conversa humana é separada da Valéria.'] },
  { perfil: 'CLIENTE', assunto: 'PERFIL', titulo: 'Meu perfil', rota: '/cliente/barbearia/:barbeariaId/perfil', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaPerfil.tsx', descricao: 'Dados do próprio cliente na barbearia selecionada.', passos: ['Abra Perfil.', 'Confira os campos e opções disponíveis para sua conta.'] },
];

export function ferramentaAjuda(papel: ContextoIa['papel']) {
  const artigos = guiaSistema.filter(a => a.perfil === papel);
  return { type: 'function', name: 'consultar_ajuda_sistema', strict: true,
    description: 'Encontra onde fica uma função, para que serve e como usá-la no perfil atual. Retorna passos e caminho interno reais. Só orientação; não executa ações.',
    parameters: { type: 'object', additionalProperties: false, properties: { assunto: { type: 'string', enum: artigos.map(a => a.assunto), description: artigos.filter(a => a.quandoUsar).map(a => `${a.assunto}: ${a.quandoUsar}`).join(' ') } }, required: ['assunto'] } };
}

/** Perguntas explícitas de uso exigem evidência atual, mesmo após falar de produção. */
export function pedeOrientacaoSistema(mensagem: string) {
  const normalizada = mensagem.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
  return /\b(como|onde|qual (?:tela|aba|menu|botao)|o que significa)\b/.test(normalizada)
    && /\b(sistema|lancar|registrar|cadastrar|criar|concluir|agendar|vender|comprar|repor|ajustar|produto|produtos|servico|atendimento|producao|financeiro|comiss(?:ao|oes)|estoque|fidelidade|configurac(?:ao|oes)|relatorio|menu|tela|aba|botao)\b/.test(normalizada);
}

export async function consultarAjuda(db: PrismaClient, c: ContextoIa, args: unknown, signal?: AbortSignal) {
  signal?.throwIfAborted();
  if (!args || typeof args !== 'object' || Array.isArray(args) || Object.keys(args).length !== 1 || !('assunto' in args) || typeof args.assunto !== 'string') throw new ErroDeNegocio('Assunto de ajuda inválido.');
  const artigo = guiaSistema.find(a => a.perfil === c.papel && a.assunto === args.assunto);
  if (!artigo) throw new ErroDeNegocio('Essa orientação não está disponível para seu perfil.', 403);
  const ativo = await db.barbearia.findFirst({ where: { id: c.barbeariaId, ativo: true }, select: { id: true } });
  const autorizado = ativo && (c.papel === 'ADMIN' ? await db.usuario.findFirst({ where: { id: c.usuarioId, papel: 'ADMIN', barbeariaId: c.barbeariaId }, select: { id: true } })
    : c.papel === 'BARBEIRO' ? await db.barbeiro.findFirst({ where: { usuarioId: c.usuarioId, barbeariaId: c.barbeariaId, ativo: true, usuario: { papel: 'BARBEIRO', barbeariaId: c.barbeariaId } }, select: { id: true } })
      : c.papel === 'CLIENTE' && c.clienteId ? await db.clienteBarbearia.findFirst({ where: { barbeariaId: c.barbeariaId, clienteId: c.clienteId, ativo: true, cliente: { usuarioId: c.usuarioId, usuario: { papel: 'CLIENTE' } } }, select: { id: true } }) : null);
  if (!autorizado) throw new ErroDeNegocio('Acesso não autorizado à ajuda desta barbearia.', 403);
  return { versao: VERSAO_GUIA, titulo: artigo.titulo, link: artigo.rota.replace(':barbeariaId', encodeURIComponent(c.barbeariaId)),
    descricao: artigo.descricao, passos: artigo.passos, limites: [...(artigo.limites ?? []), 'A Valéria orienta; somente a pessoa pode executar essas ações na interface, sujeita às permissões e ao estado da assinatura.'] };
}
