import { PrismaClient } from '@prisma/client';
import { ContextoIa } from './cotas';
import { ErroDeNegocio } from '../../lib/erros';

type Artigo = { perfil: ContextoIa['papel']; assunto: string; titulo: string; rota: string; fonte: string; descricao: string; passos: string[]; limites?: string[] };
export const VERSAO_GUIA = '2026-09-27';
// Fonte única da ajuda. Rotas e arquivos de origem são conferidos no teste.
export const guiaSistema: Artigo[] = [
  { perfil: 'ADMIN', assunto: 'AGENDA', titulo: 'Agenda', rota: '/admin/agenda', fonte: 'frontend/src/pages/Agenda.tsx', descricao: 'Organiza agendamentos por data e barbeiro.', passos: ['Abra Agenda no menu.', 'Para cadastrar, use Novo Agendamento e informe cliente, serviços, barbeiro e horário.', 'Abra um agendamento existente para ver as ações disponíveis.'] },
  { perfil: 'ADMIN', assunto: 'PRODUCAO', titulo: 'Produção dos barbeiros', rota: '/admin/barbeiros', fonte: 'frontend/src/pages/Barbeiros.tsx', descricao: 'O relatório de produção soma serviços lançados após descontos, antes de comissão, por data financeira; inclui manuais consistentes. Não é caixa bancário nem comissão.', passos: ['Abra Barbeiros.', 'Abra a produção do profissional e escolha o período. Para comparar todos, peça o ranking à Valéria.'], limites: ['Produtos, cancelados, fechamentos duplicados e registros inconsistentes ficam fora do cálculo de produção.'] },
  { perfil: 'ADMIN', assunto: 'CAIXA', titulo: 'Financeiro', rota: '/admin/financeiro', fonte: 'frontend/src/pages/Financeiro.tsx', descricao: 'Registra entradas e saídas por data e meio de pagamento. Comissão é a parte do profissional; saldo de caixa não é lucro líquido.', passos: ['Abra Financeiro.', 'Para lançar, abra Novo Lançamento, confira tipo, categoria, valor, data e forma de pagamento.', 'Revise os dados e use Registrar.'], limites: ['A Valéria orienta, mas não registra lançamentos.', 'Recebimentos são os valores informados no sistema, sem conciliação bancária automática.'] },
  { perfil: 'ADMIN', assunto: 'COMISSOES', titulo: 'Comissões', rota: '/admin/barbeiros', fonte: 'frontend/src/pages/Barbeiros.tsx', descricao: 'O cadastro do barbeiro tem percentual de comissão. Os lançamentos guardam a comissão histórica aplicada.', passos: ['Abra Barbeiros para conferir o percentual do profissional.', 'Use os relatórios de produção e financeiro para conferir valores históricos.'], limites: ['Mudar o percentual atual não significa recalcular o histórico.'] },
  { perfil: 'ADMIN', assunto: 'ESTOQUE', titulo: 'Estoque e vendas de produtos', rota: '/admin/vendas', fonte: 'frontend/src/pages/Vendas.tsx', descricao: 'Controla produtos, quantidades, custos, preços, carrinho e histórico de vendas.', passos: ['Abra Estoque no menu, cujo endereço é /admin/vendas.', 'Use Novo produto para cadastrar ou adicione produtos ao carrinho para vender.', 'No Histórico de vendas, confira a venda e use Estornar venda quando necessário.'], limites: ['Estorno não é exclusão do histórico.', 'Margem bruta usa custo histórico e desconto da venda; preço de tabela atual não prova preço passado.'] },
  { perfil: 'ADMIN', assunto: 'CLIENTES', titulo: 'Clientes', rota: '/admin/clientes', fonte: 'frontend/src/pages/Clientes.tsx', descricao: 'Consulta e administra os clientes vinculados à barbearia.', passos: ['Abra Clientes.', 'Localize a pessoa antes de abrir o cadastro e as ações disponíveis.'], limites: ['Registros com histórico devem ser preservados; não trate desativar como apagar histórico.'] },
  { perfil: 'ADMIN', assunto: 'SERVICOS', titulo: 'Serviços', rota: '/admin/servicos', fonte: 'frontend/src/pages/Servicos.tsx', descricao: 'Mantém o catálogo de serviços usado nos agendamentos.', passos: ['Abra Serviços.', 'Confira nome, preço e duração antes de salvar um cadastro.'] },
  { perfil: 'ADMIN', assunto: 'FIDELIDADE', titulo: 'Fidelidade', rota: '/admin/fidelidade', fonte: 'frontend/src/pages/admin/Fidelidade.tsx', descricao: 'Configura regras de pontos, recompensas e acompanha o histórico.', passos: ['Abra Fidelidade.', 'Escolha a área de regras, recompensas ou histórico conforme o que precisa conferir.'], limites: ['Pontos e descontos dependem das regras configuradas; não prometa saldo ou resgate sem consulta autorizada.'] },
  { perfil: 'ADMIN', assunto: 'RELATORIOS', titulo: 'Relatórios', rota: '/admin/relatorios', fonte: 'frontend/src/pages/Relatorios.tsx', descricao: 'Consulta resultados com filtros. Produção, receita de produtos, comissão e recebimentos são medidas diferentes.', passos: ['Abra Relatórios.', 'Defina o período e os filtros antes de comparar os valores.'] },
  { perfil: 'ADMIN', assunto: 'CONFIGURACOES', titulo: 'Configurações', rota: '/admin/configuracoes', fonte: 'frontend/src/pages/Configuracoes.tsx', descricao: 'Organiza dados da barbearia, funcionamento, regras do sistema e assinatura.', passos: ['Abra Configurações.', 'Selecione Barbearia, Funcionamento, Sistema ou Assinatura conforme a alteração.'], limites: ['A Valéria não altera configurações nem permissões.'] },
  { perfil: 'ADMIN', assunto: 'ASSINATURA', titulo: 'Assinatura', rota: '/admin/configuracoes?secao=assinatura', fonte: 'frontend/src/pages/Configuracoes.tsx', descricao: 'Exibe plano, cobrança e cancelamento da assinatura.', passos: ['Abra Configurações e selecione Assinatura.', 'Confira o estado mostrado antes de solicitar mudanças.'], limites: ['Acesso de consulta/exportação pode bloquear alterações. O guia não modifica plano nem cobrança.'] },
  { perfil: 'ADMIN', assunto: 'CHAT', titulo: 'Chat com clientes', rota: '/admin/chat', fonte: 'frontend/src/pages/admin/AdminChat.tsx', descricao: 'Conversas humanas com clientes vinculados.', passos: ['Abra Chat.', 'Selecione a conversa antes de enviar uma mensagem.'], limites: ['O chat humano é separado da conversa com a Valéria.'] },
  { perfil: 'BARBEIRO', assunto: 'AGENDA', titulo: 'Minha agenda', rota: '/barbeiro/agenda', fonte: 'frontend/src/pages/barbeiro/BarbeiroAgenda.tsx', descricao: 'Consulta a agenda do barbeiro autenticado.', passos: ['Abra Agenda no menu do barbeiro.', 'Selecione a data e confira os atendimentos.'], limites: ['Não dá acesso à agenda administrativa de outros profissionais.'] },
  { perfil: 'BARBEIRO', assunto: 'HOJE', titulo: 'Atendimentos de hoje', rota: '/barbeiro/hoje', fonte: 'frontend/src/pages/barbeiro/BarbeiroHoje.tsx', descricao: 'Acompanha os atendimentos do dia do profissional autenticado.', passos: ['Abra Hoje.', 'Abra um atendimento para conferir as ações que o sistema permite.'] },
  { perfil: 'BARBEIRO', assunto: 'COMISSOES', titulo: 'Minhas comissões', rota: '/barbeiro/comissoes', fonte: 'frontend/src/pages/barbeiro/BarbeiroComissoes.tsx', descricao: 'Exibe valores e lançamentos de comissão do próprio profissional.', passos: ['Abra Comissões.', 'Ajuste início e fim e confira o Histórico de Lançamentos.'], limites: ['Comissão não é o valor total produzido nem o caixa da barbearia.', 'A Valéria orienta onde consultar; a ferramenta administrativa de dados não está disponível neste perfil.'] },
  { perfil: 'BARBEIRO', assunto: 'PERFIL', titulo: 'Meu perfil', rota: '/barbeiro/perfil', fonte: 'frontend/src/pages/barbeiro/BarbeiroPerfil.tsx', descricao: 'Informações do barbeiro autenticado.', passos: ['Abra Perfil.', 'Confira os campos e controles disponíveis para sua conta.'] },
  { perfil: 'CLIENTE', assunto: 'AGENDA', titulo: 'Agendar e acompanhar', rota: '/cliente/barbearia/:barbeariaId/agendar', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaAgendar.tsx', descricao: 'Permite escolher serviços, profissional e horário disponível na barbearia selecionada.', passos: ['Na barbearia, abra Agendar.', 'Escolha serviços, profissional e horário; confira o resumo antes de confirmar.', 'Volte a Início para acompanhar seus agendamentos.'], limites: ['A Valéria não conhece disponibilidade em tempo real nem confirma agendamentos por conversa.'] },
  { perfil: 'CLIENTE', assunto: 'FIDELIDADE', titulo: 'Minha fidelidade', rota: '/cliente/barbearia/:barbeariaId/fidelidade', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaFidelidade.tsx', descricao: 'Mostra pontos e recompensas do próprio cliente nessa barbearia.', passos: ['Abra Fidelidade.', 'Confira saldo e recompensas disponíveis.', 'Para solicitar uma recompensa, use Resgatar e siga a confirmação exibida; o caixa confirma o resgate na visita.'], limites: ['Regras e elegibilidade dependem da configuração e do saldo real.'] },
  { perfil: 'CLIENTE', assunto: 'HISTORICO', titulo: 'Meu histórico', rota: '/cliente/barbearia/:barbeariaId/historico', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaHistorico.tsx', descricao: 'Consulta o histórico do próprio cliente na barbearia.', passos: ['Abra o histórico dentro da barbearia selecionada.', 'Confira os registros exibidos para sua conta.'] },
  { perfil: 'CLIENTE', assunto: 'CHAT', titulo: 'Falar com a barbearia', rota: '/cliente/barbearia/:barbeariaId/chat', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaChat.tsx', descricao: 'Canal de conversa humana com a barbearia.', passos: ['Use Falar com a barbearia, o botão de chat.', 'Escreva sua mensagem para a equipe.'], limites: ['A conversa humana é separada da Valéria.'] },
  { perfil: 'CLIENTE', assunto: 'PERFIL', titulo: 'Meu perfil', rota: '/cliente/barbearia/:barbeariaId/perfil', fonte: 'frontend/src/pages/cliente/barbearia/ClienteBarbeariaPerfil.tsx', descricao: 'Dados do próprio cliente na barbearia selecionada.', passos: ['Abra Perfil.', 'Confira os campos e opções disponíveis para sua conta.'] },
];

export function ferramentaAjuda(papel: ContextoIa['papel']) {
  return { type: 'function', name: 'consultar_ajuda_sistema', strict: true,
    description: 'Encontra onde fica uma função, para que serve e como usá-la no perfil atual. Retorna passos e caminho interno reais. Só orientação; não executa ações.',
    parameters: { type: 'object', additionalProperties: false, properties: { assunto: { type: 'string', enum: guiaSistema.filter(a => a.perfil === papel).map(a => a.assunto) } }, required: ['assunto'] } };
}

export async function consultarAjuda(db: PrismaClient, c: ContextoIa, args: unknown, signal?: AbortSignal) {
  signal?.throwIfAborted();
  if (!args || typeof args !== 'object' || Array.isArray(args) || Object.keys(args).length !== 1 || !('assunto' in args) || typeof args.assunto !== 'string') throw new ErroDeNegocio('Assunto de ajuda inválido.');
  const artigo = guiaSistema.find(a => a.perfil === c.papel && a.assunto === args.assunto);
  if (!artigo) throw new ErroDeNegocio('Essa orientação não está disponível para seu perfil.', 403);
  const ativo = await db.barbearia.findFirst({ where: { id: c.barbeariaId, ativo: true }, select: { id: true } });
  const autorizado = ativo && (c.papel === 'ADMIN' ? await db.usuario.findFirst({ where: { id: c.usuarioId, papel: 'ADMIN', barbeariaId: c.barbeariaId }, select: { id: true } })
    : c.papel === 'BARBEIRO' ? await db.barbeiro.findFirst({ where: { usuarioId: c.usuarioId, barbeariaId: c.barbeariaId, ativo: true, usuario: { papel: 'BARBEIRO', barbeariaId: c.barbeariaId } }, select: { id: true } })
      : c.papel === 'CLIENTE' && c.clienteId ? await db.clienteBarbearia.findFirst({ where: { barbeariaId: c.barbeariaId, clienteId: c.clienteId, ativo: true, cliente: { usuarioId: c.usuarioId, usuario: { papel: 'CLIENTE' } } }, select: { id: true } }) : null);
  if (!autorizado) throw new ErroDeNegocio('Acesso não autorizado à ajuda desta barbearia.', 403);
  return { versao: VERSAO_GUIA, titulo: artigo.titulo, link: artigo.rota.replace(':barbeariaId', encodeURIComponent(c.barbeariaId)),
    descricao: artigo.descricao, passos: artigo.passos, limites: [...(artigo.limites ?? []), 'A Valéria orienta; somente a pessoa pode executar essas ações na interface, sujeita às permissões e ao estado da assinatura.'] };
}
